### ISSUE TITLE
My axe is not working

### ISSUE THREAD

**Issue by WolfMethod** [TheWinABagel/Decorative-Blocks#1]
When I installed this mod, suddenly all blocks that are breakable with an axe started to be broken slowly, same speed as if I was breaking them with an empty hand.

I play on Minecraft 1.20.1 with Forge 47.1.0

**Comment by achhandrian** [comment]
And leaves are despawning, the block tags seems to be broken with the mod.
Playing on 1.20.1 Fabric, only haviun the fabric api and no other mods for a test
![Bild_2023-08-16_221540614](https://github.com/TheWinABagel/Decorative-Blocks/assets/74990775/bc6b7aae-a39d-4d39-b210-c1654bdad3b0)

**Comment by TheWinABagel** [comment]
Fixed with 03fa8a3
