### ISSUE TITLE
1.20.1-4.0.2 crashing my modpack

### ISSUE THREAD

**Issue by ginsm** [TheWinABagel/Decorative-Blocks#3]
Hey there,

This might just be modpack specific; some conflict somewhere in the pack.. but I was crashing whilst having this fork installed, here's the log:

https://paste.atlauncher.com/view/0305eec9-a838-451a-a251-06e86927092a

If the log isn't too helpful (doesn't seem to be really) feel free to just close the issue. I figured I'd share it though in case you notice what it might be and can fix it.

**Comment by TheWinABagel** [comment]
Will be fixed next update (4.0.3), it's a conflict with lithium.
