### ISSUE TITLE
Crash on Fabric 0.14.22-1.20.1 with Lithium 1.20.1-0.11.2

### ISSUE THREAD

**Issue by GJdude** [TheWinABagel/Decorative-Blocks#4]
Loading this mod together with Lithium will immediately crash the game to the launcher. Happens with both version 4.0.0 and 4.0.2 of Decorative Blocks.

**Comment by VinceKezel** [comment]
I found a fix that works for my server setup running lithium + decorative blocks. In lithium's config, I put this:
`mixin.util.chunk_access=false`

**Comment by GJdude** [comment]
I can confirm that makes it work! What does that config option actually do, though?

**Comment by VinceKezel** [comment]
I don't know.... I know the config has the comment " *Access chunks of worlds, chunk caches and chunk regions directly.* " but I don't know that means.... and why it crashes when attempting.

**Comment by TheWinABagel** [comment]
Have been busy with IRL stuff, but the next version (4.0.3) will fix this, apologies for the wait!
