### ISSUE TITLE
Add Forge Config API Port dependency to Fabric releases on CF, MR and FMJ

### ISSUE THREAD

**Issue by Poopooracoocoo** [TheWinABagel/Decorative-Blocks#7]
At first I found that using the Fabric version of the mod for Minecraft 1.19.2 lead to a crash.

**Environment:**
Minecraft 1.19.2
Fabric Loader 0.14.23
Fabric API 0.76.1
Architectury 6.5.85
Decorative Blocks 3.1.1

**Crash report:**
https://mclo.gs/OCQSXKp
[crash-2023-10-17_07.56.07-client.txt](https://github.com/TheWinABagel/Decorative-Blocks/files/12921805/crash-2023-10-17_07.56.07-client.txt)

**Logs:**
https://mclo.gs/YDKyZph
[latest.log](https://github.com/TheWinABagel/Decorative-Blocks/files/12921997/latest.log)

>Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/common/ForgeConfigSpec$ConfigValue

But after I had a look at the log, I realised that I could try adding Forge Config API Port and it launched successfully.

Could you please add the Forge Config API Port dependency to the release on CurseForge and Modrinth and to the depends section of your fabric.mod.json? Thank you :)

**Comment by TheWinABagel** [comment]
Oh yeah, I completely forgot about that! Thanks for letting me know, will do

**Comment by Poopooracoocoo** [comment]
I just saw this issue in the wild again in a Discord server and noticed that the latest releases on Modrinth for 1.19.2 and 1.20.1 don't have this dependency (and they were created before this issue so they don't have them in their FMJ either) 

So just here to remind you :)
